import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "../../api/api";
import Button from "../../lib/Button";

type Entry={financeAccountId:number;accountName:string;ledgerCode:string|null;accountType:string|number;displayOrder:number;debitAmount:number;creditAmount:number;note:string|null};
type Audit={action:string;userId:number|null;occurredAt:string;note:string|null};
type SetRow={id:number;asAtDate:string;isCommitted:boolean;committedAt:string|null;totalDebits:number;totalCredits:number;difference:number;entries:Entry[];auditEntries:Audit[];concurrencyToken:string};
const typeLabel:Record<string,string>={Cash:"Cash & Bank",Bank:"Cash & Bank",MobileWallet:"Cash & Bank",Other:"Cash & Bank",FixedAsset:"Fixed Assets",WorkInProgress:"Work in Progress",Receivable:"Receivables",Liability:"Liabilities",Capital:"Capital","1":"Cash & Bank","2":"Cash & Bank","3":"Cash & Bank","4":"Cash & Bank","5":"Liabilities","6":"Capital","7":"Fixed Assets","8":"Receivables","9":"Work in Progress"};
const money=(value:number)=>`Rs ${value.toLocaleString("en-PK",{maximumFractionDigits:2})}`;
const today=()=>{const date=new Date(),pad=(value:number)=>String(value).padStart(2,"0");return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;};

export default function OpeningBalancesPanel(){
  const [row,setRow]=useState<SetRow|null>(null),[date,setDate]=useState(today()),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await api("/api/finance/opening-balances/current");if(!response.ok)throw new Error("Opening balances could not be loaded.");setRow(await response.json());}catch(caught){setError(caught instanceof Error?caught.message:"Opening balances could not be loaded.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const totals=useMemo(()=>({debit:row?.entries.reduce((sum,entry)=>sum+(Number(entry.debitAmount)||0),0)??0,credit:row?.entries.reduce((sum,entry)=>sum+(Number(entry.creditAmount)||0),0)??0}),[row]);
  const difference=Math.round((totals.debit-totals.credit)*100)/100;
  const create=async()=>{setBusy(true);setError(null);try{const response=await api("/api/finance/opening-balances",{method:"POST",body:JSON.stringify({asAtDate:date})});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message??"Opening balance set could not be created.");setRow(await response.json());}catch(caught){setError(caught instanceof Error?caught.message:"Opening balance set could not be created.");}finally{setBusy(false);}};
  const save=async()=>{if(!row)return;setBusy(true);setError(null);try{const response=await api(`/api/finance/opening-balances/${row.id}`,{method:"PUT",body:JSON.stringify({entries:row.entries.map(entry=>({financeAccountId:entry.financeAccountId,debitAmount:Number(entry.debitAmount)||0,creditAmount:Number(entry.creditAmount)||0,note:entry.note||null})),concurrencyToken:row.concurrencyToken})});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message??"Opening balances could not be saved.");setRow(await response.json());}catch(caught){setError(caught instanceof Error?caught.message:"Opening balances could not be saved.");}finally{setBusy(false);}};
  const commit=async()=>{if(!row||difference!==0)return;if(!window.confirm("Commit these opening balances? They become the baseline for every historical report and will be locked."))return;setBusy(true);setError(null);try{const response=await api(`/api/finance/opening-balances/${row.id}/commit`,{method:"POST",body:JSON.stringify({concurrencyToken:row.concurrencyToken})});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message??"Opening balances could not be committed.");setRow(await response.json());}catch(caught){setError(caught instanceof Error?caught.message:"Opening balances could not be committed.");}finally{setBusy(false);}};
  const reopen=async()=>{if(!row)return;if(!window.confirm("Reopening and recommitting opening balances changes every report from the go-live date onward. Continue?"))return;setBusy(true);setError(null);try{const response=await api(`/api/finance/opening-balances/${row.id}/reopen`,{method:"POST",body:JSON.stringify({warningAccepted:true,note:"Reopened from Finance settings",concurrencyToken:row.concurrencyToken})});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message??"Opening balances could not be reopened.");setRow(await response.json());}catch(caught){setError(caught instanceof Error?caught.message:"Opening balances could not be reopened.");}finally{setBusy(false);}};
  const change=(id:number,field:"debitAmount"|"creditAmount"|"note",value:string)=>{if(!row||row.isCommitted)return;setRow({...row,entries:row.entries.map(entry=>entry.financeAccountId===id?{...entry,[field]:field==="note"?value:Number(value),...(field==="debitAmount"&&Number(value)>0?{creditAmount:0}:{}),...(field==="creditAmount"&&Number(value)>0?{debitAmount:0}:{})}:entry)});};
  if(loading)return <p className="py-16 text-center text-sm text-[var(--text-muted)]">Loading opening balances…</p>;
  return <div><h2 className="text-lg font-semibold text-[var(--text-heading)]">Opening balances</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Enter the verified go-live trial balance as debits and credits. A set cannot be committed until it balances exactly.</p>{error&&<p className="mt-4 rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</p>}
  {!row?<div className="mt-6 flex items-end gap-3"><label className="text-sm text-[var(--text-muted)]">Go-live date<input className="mt-1 block rounded-xl border border-[var(--border)] bg-[var(--input-bg)] p-3" type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><Button disabled={busy} onClick={()=>void create()}>Create opening balance set</Button></div>:<>
  <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm"><strong>As at {new Date(row.asAtDate).toLocaleDateString("en-GB")}</strong> · {row.isCommitted?`Committed ${row.committedAt?new Date(row.committedAt).toLocaleString("en-GB"):""}`:"Draft"}</p><div className="flex gap-2">{row.isCommitted?<Button variant="outline" disabled={busy} onClick={()=>void reopen()}>Reopen with warning</Button>:<><Button variant="outline" disabled={busy} onClick={()=>void save()}>Save draft</Button><Button disabled={busy||difference!==0} onClick={()=>void commit()}>Commit balances</Button></>}</div></div>
  <div className="mt-4 overflow-x-auto rounded-xl border border-[var(--border)]"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-[var(--border)] text-left text-[var(--text-muted)]"><th className="p-3">Account</th><th className="p-3">Group</th><th className="p-3 text-right">Debit</th><th className="p-3 text-right">Credit</th><th className="p-3">Note</th></tr></thead><tbody>{row.entries.map(entry=><tr key={entry.financeAccountId} className="border-b border-[var(--border)]"><td className="p-3 font-medium">{entry.ledgerCode?`${entry.ledgerCode} · `:""}{entry.accountName}</td><td className="p-3 text-[var(--text-muted)]">{typeLabel[String(entry.accountType)]??String(entry.accountType)}</td><td className="p-3"><input aria-label={`${entry.accountName} debit`} disabled={row.isCommitted} type="number" min="0" step="0.01" className="w-36 rounded-lg border border-[var(--border)] bg-[var(--input-bg)] p-2 text-right" value={entry.debitAmount||""} onChange={event=>change(entry.financeAccountId,"debitAmount",event.target.value)}/></td><td className="p-3"><input aria-label={`${entry.accountName} credit`} disabled={row.isCommitted} type="number" min="0" step="0.01" className="w-36 rounded-lg border border-[var(--border)] bg-[var(--input-bg)] p-2 text-right" value={entry.creditAmount||""} onChange={event=>change(entry.financeAccountId,"creditAmount",event.target.value)}/></td><td className="p-3"><input disabled={row.isCommitted} className="w-full min-w-48 rounded-lg border border-[var(--border)] bg-[var(--input-bg)] p-2" value={entry.note??""} onChange={event=>change(entry.financeAccountId,"note",event.target.value)}/></td></tr>)}</tbody><tfoot><tr className="font-bold"><td colSpan={2} className="p-3">Totals</td><td className="p-3 text-right">{money(totals.debit)}</td><td className="p-3 text-right">{money(totals.credit)}</td><td className={`p-3 ${difference===0?"text-emerald-300":"text-rose-300"}`}>Difference: {money(difference)}</td></tr></tfoot></table></div>
  {row.auditEntries.length>0&&<details className="mt-4 text-sm"><summary className="cursor-pointer text-[var(--accent)]">Audit history</summary><div className="mt-2 space-y-1">{row.auditEntries.map((audit,index)=><p key={`${audit.occurredAt}-${index}`} className="text-[var(--text-muted)]">{new Date(audit.occurredAt).toLocaleString("en-GB")} · {audit.action}{audit.note?` · ${audit.note}`:""}</p>)}</div></details>}
  </>}</div>;
}
