import pkg from 'file:///C:/Users/PC/AppData/Local/npm-cache/_npx/e41f203b7505f1fb/node_modules/playwright/index.js';
const { chromium } = pkg;
const SD = process.env.SD;
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await ctx.newPage();
page.setDefaultTimeout(15000);
await page.goto('http://localhost:5173/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(2500);
await page.getByRole('button', { name: /^Log in$/i }).first().click();
await page.waitForTimeout(600);
await page.locator('input[type="email"]').fill('riazjunaid64@gmail.com');
await page.locator('input[type="password"]').fill('1234');
await page.getByRole('button', { name: /sign in|log in/i }).last().click();
await page.waitForTimeout(3500);
await page.goto('http://localhost:5173/finance', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(3500);
await page.screenshot({ path: SD + '/admin-finance2.png' });
console.log('done');
await b.close();
