import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { Link, useNavigate } from "react-router-dom";
import type { User } from "../App";
import Button from "../lib/Button";
import Container from "../lib/Container";
import Field from "../lib/Field";
import { commissionRebateApi } from "../features/commissionRebates/api";
import { money, pakistanToday, prettyEnum, trapDialogKeys } from "../features/commissionRebates/state";
import type { Commission, CommissionRebateSummary, CommissionRule, Partner, Rebate } from "../features/commissionRebates/types";

type View = "overview"|"partners"|"rules"|"commissions"|"rebates";
type PartnerForm = {id?:number;name:string;partnerType:string;internalCode:string;contactPerson:string;phone:string;email:string;cnic:string;ntn:string;registrationNumber:string;address:string;bankName:string;accountTitle:string;accountNumber:string;iban:string;notes:string;concurrencyToken?:string};
type RuleForm = {id?:number;name:string;description:string;isActive:boolean;effectiveFrom:string;effectiveTo:string;partnerId:string;partnerType:string;projectId:string;unitCategory:string;bookingSource:string;bookingId:string;calculationType:"Percentage"|"FixedAmount";percentageRate:string;fixedAmount:string;calculationBasis:string;minimumCommission:string;maximumCommission:string;priority:string;notes:string;changeReason:string;concurrencyToken?:string};

const partnerTypes=["Broker","Dealer","Agency","Referral Partner","Introducer","Marketing Partner","External Sales Agent","Other"];
const bases=["AgreedSalePrice","NetSalePriceAfterDiscount","BookingAmountReceived","AmountActuallyCollected"];
const emptyPartner=():PartnerForm=>({name:"",partnerType:"Broker",internalCode:"",contactPerson:"",phone:"",email:"",cnic:"",ntn:"",registrationNumber:"",address:"",bankName:"",accountTitle:"",accountNumber:"",iban:"",notes:""});
const emptyRule=():RuleForm=>({name:"",description:"",isActive:true,effectiveFrom:pakistanToday(),effectiveTo:"",partnerId:"",partnerType:"",projectId:"",unitCategory:"",bookingSource:"",bookingId:"",calculationType:"Percentage",percentageRate:"",fixedAmount:"",calculationBasis:"NetSalePriceAfterDiscount",minimumCommission:"",maximumCommission:"",priority:"0",notes:"",changeReason:"Initial rule configuration"});
const selectClass="w-full rounded-xl border border-[var(--border)] bg-[var(--input-bg)] px-4 py-3 text-sm text-[var(--text-primary)]";
// Every status a record can be in. Pending covers part-paid too, so the Paid and Remaining columns
// are what separate "nothing paid yet" from "half way there".
const commissionFilters=[{v:"Pending",n:"Pending"},{v:"Paid",n:"Paid"},{v:"Cancelled",n:"Cancelled"},
  {v:"ReversalRequired",n:"Recovery required"},{v:"Reversed",n:"Reversed"}];
const rebateFilters=[{v:"Pending",n:"Pending"},{v:"Applied",n:"Applied"},{v:"Paid",n:"Paid"},
  {v:"Cancelled",n:"Cancelled"},{v:"ReversalRequired",n:"Recovery required"},{v:"Reversed",n:"Reversed"}];

export default function CommissionRebatesPage({user}:{user:User|null}){
  const navigate=useNavigate();
  const [view,setView]=useState<View>("overview"),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
  const [summary,setSummary]=useState<CommissionRebateSummary|null>(null),[partners,setPartners]=useState<Partner[]>([]),[partnerOptions,setPartnerOptions]=useState<Partner[]>([]),[rules,setRules]=useState<CommissionRule[]>([]),[commissions,setCommissions]=useState<Commission[]>([]),[rebates,setRebates]=useState<Rebate[]>([]);
  const [search,setSearch]=useState(""),[partnerStatus,setPartnerStatus]=useState("active"),[recordStatus,setRecordStatus]=useState("");
  const [partnerPage,setPartnerPage]=useState(0),[partnerHasMore,setPartnerHasMore]=useState(false);
  const [rulePage,setRulePage]=useState(0),[ruleHasMore,setRuleHasMore]=useState(false),[rulesLoading,setRulesLoading]=useState(false);
  const [commissionPage,setCommissionPage]=useState(0),[commissionHasMore,setCommissionHasMore]=useState(false),[rebatePage,setRebatePage]=useState(0),[rebateHasMore,setRebateHasMore]=useState(false),[recordsLoading,setRecordsLoading]=useState(false);
  const [partnerForm,setPartnerForm]=useState<PartnerForm|null>(null),[ruleForm,setRuleForm]=useState<RuleForm|null>(null),[saving,setSaving]=useState(false),[formError,setFormError]=useState<string|null>(null);
  const partnerLoadSequence=useRef(0),workspaceLoadSequence=useRef(0),recordLoadSequence=useRef(0),ruleLoadSequence=useRef(0);
  const loadPartners=useCallback(async()=>{const request=++partnerLoadSequence.current;const active=partnerStatus==="all"?undefined:partnerStatus==="active";try{const result=await commissionRebateApi.partners(search.trim(),active,partnerPage*25,25);if(request!==partnerLoadSequence.current)return;setPartners(result.items);setPartnerHasMore(result.hasMore);}catch(e){if(request===partnerLoadSequence.current)throw e;}},[search,partnerStatus,partnerPage]);
  const load=useCallback(async()=>{const request=++workspaceLoadSequence.current;setLoading(true);setError(null);try{const [s,p]=await Promise.all([commissionRebateApi.summary(),commissionRebateApi.partners("",undefined,0,500)]);if(request!==workspaceLoadSequence.current)return;setSummary(s);setPartnerOptions(p.items);}catch(e){if(request===workspaceLoadSequence.current)setError(e instanceof Error?e.message:"The commission workspace could not be loaded.");}finally{if(request===workspaceLoadSequence.current)setLoading(false);}},[]);
  // Rules are paged (25 per page) so every rule stays reachable even beyond the first page — a flat
  // capped fetch would leave later rules invisible in the directory.
  const loadRules=useCallback(async()=>{const request=++ruleLoadSequence.current;setRulesLoading(true);try{const result=await commissionRebateApi.rules(undefined,rulePage*25,25);if(request!==ruleLoadSequence.current)return;setRules(result.items);setRuleHasMore(result.hasMore);}catch(e){if(request===ruleLoadSequence.current)setError(e instanceof Error?e.message:"Commission rules could not be loaded.");}finally{if(request===ruleLoadSequence.current)setRulesLoading(false);}},[rulePage]);
  const loadRecords=useCallback(async()=>{if(view!=="commissions"&&view!=="rebates")return;const request=++recordLoadSequence.current;setRecordsLoading(true);setError(null);try{if(view==="commissions"){const result=await commissionRebateApi.commissions(recordStatus,commissionPage*25,25);if(request!==recordLoadSequence.current)return;setCommissions(result.items);setCommissionHasMore(result.hasMore);}else{const result=await commissionRebateApi.rebates(recordStatus,rebatePage*25,25);if(request!==recordLoadSequence.current)return;setRebates(result.items);setRebateHasMore(result.hasMore);}}catch(e){if(request===recordLoadSequence.current)setError(e instanceof Error?e.message:"Financial records could not be loaded.");}finally{if(request===recordLoadSequence.current)setRecordsLoading(false);}},[view,recordStatus,commissionPage,rebatePage]);
  useEffect(()=>{if(user?.role!=="Admin"){navigate("/");return;}void load();},[user,navigate,load]);
  useEffect(()=>{if(user?.role!=="Admin")return;const timer=window.setTimeout(()=>{void loadPartners().catch(e=>setError(e instanceof Error?e.message:"Partners could not be loaded."));},250);return()=>window.clearTimeout(timer);},[user,loadPartners]);
  useEffect(()=>{if(user?.role==="Admin")void loadRecords();},[user,loadRecords]);
  useEffect(()=>{if(user?.role==="Admin"&&view==="rules")void loadRules();},[user,view,loadRules]);
  const shownPartners=partners;
  const shownCommissions=commissions;
  const shownRebates=rebates;
  const editPartner=(p:Partner)=>setPartnerForm({id:p.id,name:p.name,partnerType:p.partnerType,internalCode:p.internalCode,contactPerson:p.contactPerson??"",phone:p.phone??"",email:p.email??"",cnic:p.cnic??"",ntn:p.ntn??"",registrationNumber:p.registrationNumber??"",address:p.address??"",bankName:p.bankName??"",accountTitle:p.accountTitle??"",accountNumber:p.accountNumber??"",iban:p.iban??"",notes:p.notes??"",concurrencyToken:p.concurrencyToken});
  const editRule=(r:CommissionRule)=>setRuleForm({id:r.id,name:r.name,description:r.description??"",isActive:r.isActive,effectiveFrom:r.effectiveFrom.slice(0,10),effectiveTo:r.effectiveTo?.slice(0,10)??"",partnerId:r.partnerId?.toString()??"",partnerType:r.partnerType??"",projectId:r.projectId?.toString()??"",unitCategory:r.unitCategory??"",bookingSource:r.bookingSource??"",bookingId:r.bookingId?.toString()??"",calculationType:r.calculationType,percentageRate:r.percentageRate?.toString()??"",fixedAmount:r.fixedAmount?.toString()??"",calculationBasis:r.calculationBasis,minimumCommission:r.minimumCommission?.toString()??"",maximumCommission:r.maximumCommission?.toString()??"",priority:r.priority.toString(),notes:r.notes??"",changeReason:"",concurrencyToken:r.concurrencyToken});
  const savePartner=async(e:FormEvent)=>{e.preventDefault();if(!partnerForm)return;setSaving(true);setFormError(null);try{await commissionRebateApi.savePartner({...partnerForm,contactPerson:partnerForm.contactPerson||null,phone:partnerForm.phone||null,email:partnerForm.email||null,cnic:partnerForm.cnic||null,ntn:partnerForm.ntn||null,registrationNumber:partnerForm.registrationNumber||null,address:partnerForm.address||null,bankName:partnerForm.bankName||null,accountTitle:partnerForm.accountTitle||null,accountNumber:partnerForm.accountNumber||null,iban:partnerForm.iban||null,notes:partnerForm.notes||null},partnerForm.id);setPartnerForm(null);await Promise.all([load(),loadPartners()]);}catch(x){setFormError(x instanceof Error?x.message:"Partner could not be saved.");}finally{setSaving(false);}};
  const saveRule=async(e:FormEvent)=>{e.preventDefault();if(!ruleForm)return;setSaving(true);setFormError(null);const n=(v:string)=>v===""?null:Number(v);try{await commissionRebateApi.saveRule({...ruleForm,effectiveTo:ruleForm.effectiveTo||null,partnerId:n(ruleForm.partnerId),partnerType:ruleForm.partnerType||null,projectId:n(ruleForm.projectId),unitCategory:ruleForm.unitCategory||null,bookingSource:ruleForm.bookingSource||null,bookingId:n(ruleForm.bookingId),percentageRate:ruleForm.calculationType==="Percentage"?n(ruleForm.percentageRate):null,fixedAmount:ruleForm.calculationType==="FixedAmount"?n(ruleForm.fixedAmount):null,minimumCommission:n(ruleForm.minimumCommission),maximumCommission:n(ruleForm.maximumCommission),priority:Number(ruleForm.priority)||0,notes:ruleForm.notes||null},ruleForm.id);setRuleForm(null);await loadRules();}catch(x){setFormError(x instanceof Error?x.message:"Rule could not be saved.");}finally{setSaving(false);}};
  const togglePartner=async(p:Partner)=>{const reason=p.isActive?window.prompt("Reason for deactivation:"):"Reactivated for new business";if(p.isActive&&!reason)return;try{await commissionRebateApi.partnerStatus(p.id,{isActive:!p.isActive,reason,concurrencyToken:p.concurrencyToken});await Promise.all([load(),loadPartners()]);}catch(x){setError(x instanceof Error?x.message:"Partner status could not be changed.");}};
  if(user?.role!=="Admin")return null;
  return <Container className="py-8">
    <header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><Link to="/finance" className="text-sm text-[var(--accent)]">← Finance dashboard</Link><h1 className="mt-1 text-3xl font-bold text-[var(--text-heading)]">Commissions & Rebates</h1><p className="mt-1 text-sm text-[var(--text-muted)]">Partners, calculation rules, payouts, customer benefits, and immutable history.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>navigate("/finance/accounts")}>Finance accounts</Button>{view==="partners"&&<Button onClick={()=>setPartnerForm(emptyPartner())}>Add partner</Button>}{view==="rules"&&<Button onClick={()=>setRuleForm(emptyRule())}>Add rule</Button>}</div></header>
    <nav aria-label="Commission workspace sections" className="mb-6 flex gap-2 overflow-x-auto border-b border-[var(--border)]">{(["overview","partners","rules","commissions","rebates"] as View[]).map(v=><button key={v} onClick={()=>{setView(v);setRecordStatus("");setCommissionPage(0);setRebatePage(0);setRulePage(0);}} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-semibold ${view===v?"border-[var(--accent)] text-[var(--accent)]":"border-transparent text-[var(--text-muted)]"}`}>{prettyEnum(v[0].toUpperCase()+v.slice(1))}</button>)}</nav>
    {error&&<div role="alert" className="mb-5 rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">{error}<button className="ml-3 underline" onClick={()=>{void load();void loadRecords();}}>Retry</button></div>}
    {loading?<p className="py-16 text-center text-[var(--text-muted)]">Loading financial controls…</p>:<>
      {view==="overview"&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Accrued commission" value={money(summary?.accruedCommission??0)}/><Stat label="Commission payable" value={money(summary?.payableCommission??0)}/><Stat label="Commission paid" value={money(summary?.commissionPaid??0)}/><Stat label="Rebates granted" value={money(summary?.rebatesGranted??0)}/><Stat label="Rebates completed" value={money(summary?.rebatesAppliedOrPaid??0)}/><Stat label="Pending payment" value={String(summary?.pendingRecords??0)}/><Stat label="Active partners" value={String(summary?.activePartners??0)}/><Stat label="Reversal required" value={money((summary?.commissionReversalRequired??0)+(summary?.rebateReversalRequired??0))} danger/></div><div className="mt-6 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><h2 className="font-semibold text-[var(--text-heading)]">Controlled workflow</h2><p className="mt-2 text-sm text-[var(--text-muted)]">Add commissions and rebates from Booking Detail. A record is pending from the moment it is entered and becomes paid on its own once the payments cover it; payouts, rebate application, evidence, reversals, and audit all stay in that booking context.</p></div></>}
      {view==="partners"&&<><Filters search={search} setSearch={v=>{setSearch(v);setPartnerPage(0);}} value={partnerStatus} setValue={v=>{setPartnerStatus(v);setPartnerPage(0);}} options={["all","active","inactive"]}/><Table headers={["Partner","Type","Contact","Identifiers","Use","Status","Actions"]}>{shownPartners.map(p=><tr key={p.id} className="border-b border-[var(--border)]"><Cell><strong>{p.name}</strong><small>{p.internalCode}</small></Cell><Cell>{p.partnerType}</Cell><Cell>{p.contactPerson??"—"}<small>{p.phone??p.email??""}</small></Cell><Cell>{p.cnic??p.ntn??"—"}</Cell><Cell>{p.attributionCount} attribution(s)<small>{p.commissionCount} commission(s)</small></Cell><Cell><Badge value={p.isActive?"Active":"Inactive"}/></Cell><Cell><div className="flex gap-2"><button className="text-[var(--accent)]" onClick={()=>editPartner(p)}>Edit</button><button className="text-[var(--text-muted)]" onClick={()=>void togglePartner(p)}>{p.isActive?"Deactivate":"Reactivate"}</button></div></Cell></tr>)}</Table>{shownPartners.length===0&&<Empty text="No partners match the current filters."/>}<Pager page={partnerPage} hasMore={partnerHasMore} setPage={setPartnerPage}/></>}
      {view==="rules"&&<><p className="mb-4 text-sm text-[var(--text-muted)]">Highest priority wins, then the most specific matching scope. Equally ranked matches fail safely and require explicit selection.</p><Table headers={["Rule","Scope","Calculation","Basis","Priority","Status","Actions"]}>{rules.map(r=><tr key={r.id} className="border-b border-[var(--border)]"><Cell><strong>{r.name}</strong><small>{r.effectiveFrom.slice(0,10)}{r.effectiveTo?` – ${r.effectiveTo.slice(0,10)}`:" onward"}</small></Cell><Cell>{r.partnerName??r.partnerType??r.projectName??(r.bookingId?`Booking #${r.bookingId}`:"Default")}</Cell><Cell>{r.calculationType==="Percentage"?`${r.percentageRate}%`:money(r.fixedAmount??0)}</Cell><Cell>{prettyEnum(r.calculationBasis)}</Cell><Cell>{r.priority}</Cell><Cell><Badge value={r.isActive?"Active":"Inactive"}/></Cell><Cell><button className="text-[var(--accent)]" onClick={()=>editRule(r)}>Edit</button></Cell></tr>)}</Table>{rules.length===0&&!rulesLoading&&<Empty text="No commission rules configured."/>}<Pager page={rulePage} hasMore={ruleHasMore} setPage={setRulePage}/></>}
      {view==="commissions"&&<RecordsFilter value={recordStatus} setValue={v=>{setRecordStatus(v);setCommissionPage(0);}} values={commissionFilters}/>}
      {view==="commissions"&&(recordsLoading?<p className="py-12 text-center text-sm text-[var(--text-muted)]">Loading commissions…</p>:<><Table headers={["Booking","Partner","Rule / basis","Commission","Paid","Remaining","Recovery","Status"]}>{shownCommissions.map(c=><tr key={c.id} className="border-b border-[var(--border)]"><Cell><Link className="text-[var(--accent)]" to={`/confirmed-bookings/${c.bookingId}`}>{c.bookingReference}</Link></Cell><Cell>{c.partnerName}</Cell><Cell>{c.ruleNameSnapshot??"Manual"}<small>{money(c.basisAmount)} · {prettyEnum(c.calculationBasis)}</small></Cell><Cell>{money(c.finalAmount)}</Cell><Cell>{money(c.paidAmount)}</Cell><Cell>{money(c.outstandingAmount)}</Cell><Cell>{money(c.recoveryRequiredAmount)}</Cell><Cell><Badge value={c.status}/></Cell></tr>)}</Table>{shownCommissions.length===0&&<Empty text="No commissions match the current filter."/>}<Pager page={commissionPage} hasMore={commissionHasMore} setPage={setCommissionPage}/></>)}
      {view==="rebates"&&<RecordsFilter value={recordStatus} setValue={v=>{setRecordStatus(v);setRebatePage(0);}} values={rebateFilters}/>}
      {view==="rebates"&&(recordsLoading?<p className="py-12 text-center text-sm text-[var(--text-muted)]">Loading rebates…</p>:<><Table headers={["Booking","Customer","Reason / method","Rebate","Given","Remaining","Recovery","Status"]}>{shownRebates.map(r=><tr key={r.id} className="border-b border-[var(--border)]"><Cell><Link className="text-[var(--accent)]" to={`/confirmed-bookings/${r.bookingId}`}>{r.bookingReference}</Link></Cell><Cell>{r.customerName}</Cell><Cell>{r.reason}<small>{prettyEnum(r.method)}</small></Cell><Cell>{money(r.finalAmount)}</Cell><Cell>{money(r.appliedOrPaidAmount)}</Cell><Cell>{money(r.outstandingAmount)}</Cell><Cell>{money(r.recoveryRequiredAmount)}</Cell><Cell><Badge value={r.status}/></Cell></tr>)}</Table>{shownRebates.length===0&&<Empty text="No rebates match the current filter."/>}<Pager page={rebatePage} hasMore={rebateHasMore} setPage={setRebatePage}/></>)}
    </>}
    {partnerForm&&<Modal title={partnerForm.id?"Edit partner":"Add partner"} close={()=>!saving&&setPartnerForm(null)}><form onSubmit={savePartner} className="grid gap-4 sm:grid-cols-2">{formError&&<FormError text={formError}/>}<Field label="Name" required value={partnerForm.name} onChange={e=>setPartnerForm({...partnerForm,name:e.target.value})}/><Select label="Partner type" value={partnerForm.partnerType} set={v=>setPartnerForm({...partnerForm,partnerType:v})} options={partnerTypes}/><Field label="Internal code" required value={partnerForm.internalCode} onChange={e=>setPartnerForm({...partnerForm,internalCode:e.target.value})}/><Field label="Contact person" value={partnerForm.contactPerson} onChange={e=>setPartnerForm({...partnerForm,contactPerson:e.target.value})}/><Field label="Phone" value={partnerForm.phone} onChange={e=>setPartnerForm({...partnerForm,phone:e.target.value})}/><Field label="Email" type="email" value={partnerForm.email} onChange={e=>setPartnerForm({...partnerForm,email:e.target.value})}/><Field label="CNIC" value={partnerForm.cnic} onChange={e=>setPartnerForm({...partnerForm,cnic:e.target.value})}/><Field label="NTN / tax number" value={partnerForm.ntn} onChange={e=>setPartnerForm({...partnerForm,ntn:e.target.value})}/><Field label="Registration number" value={partnerForm.registrationNumber} onChange={e=>setPartnerForm({...partnerForm,registrationNumber:e.target.value})}/><Field label="Bank name" value={partnerForm.bankName} onChange={e=>setPartnerForm({...partnerForm,bankName:e.target.value})}/><Field label="Account title" value={partnerForm.accountTitle} onChange={e=>setPartnerForm({...partnerForm,accountTitle:e.target.value})}/><Field label="Account number" value={partnerForm.accountNumber} onChange={e=>setPartnerForm({...partnerForm,accountNumber:e.target.value})}/><Field label="IBAN" value={partnerForm.iban} onChange={e=>setPartnerForm({...partnerForm,iban:e.target.value})}/><div className="sm:col-span-2"><Field as="textarea" label="Address" value={partnerForm.address} onChange={e=>setPartnerForm({...partnerForm,address:e.target.value})}/></div><div className="sm:col-span-2"><Field as="textarea" label="Notes" value={partnerForm.notes} onChange={e=>setPartnerForm({...partnerForm,notes:e.target.value})}/></div><Actions saving={saving} close={()=>setPartnerForm(null)}/></form></Modal>}
    {ruleForm&&<Modal title={ruleForm.id?"Edit commission rule":"Add commission rule"} close={()=>!saving&&setRuleForm(null)}>
      <form onSubmit={saveRule} className="grid gap-4 sm:grid-cols-2">
        {formError&&<FormError text={formError}/>} 
        <Field label="Rule name" required value={ruleForm.name} onChange={e=>setRuleForm({...ruleForm,name:e.target.value})}/>
        <Field label="Priority" type="number" value={ruleForm.priority} onChange={e=>setRuleForm({...ruleForm,priority:e.target.value})}/>
        <Field label="Effective from" type="date" required value={ruleForm.effectiveFrom} onChange={e=>setRuleForm({...ruleForm,effectiveFrom:e.target.value})}/>
        <Field label="Effective to" type="date" value={ruleForm.effectiveTo} onChange={e=>setRuleForm({...ruleForm,effectiveTo:e.target.value})}/>
        <Select label="Calculation type" value={ruleForm.calculationType} set={v=>setRuleForm({...ruleForm,calculationType:v as RuleForm["calculationType"]})} options={["Percentage","FixedAmount"]}/>
        {ruleForm.calculationType==="Percentage"
          ?<Field label="Rate %" type="number" min="0.000001" max="100" step="0.000001" required value={ruleForm.percentageRate} onChange={e=>setRuleForm({...ruleForm,percentageRate:e.target.value})}/>
          :<Field label="Fixed amount" type="number" min="0.01" step="0.01" required value={ruleForm.fixedAmount} onChange={e=>setRuleForm({...ruleForm,fixedAmount:e.target.value})}/>}
        <Select label="Calculation basis" value={ruleForm.calculationBasis} set={v=>setRuleForm({...ruleForm,calculationBasis:v})} options={bases}/>
        <Select label="Specific partner" value={ruleForm.partnerId} set={v=>setRuleForm({...ruleForm,partnerId:v})} options={["",...partnerOptions.map(p=>String(p.id))]} names={["Any partner",...partnerOptions.map(p=>p.name)]}/>
        <Select label="Partner type (optional)" value={ruleForm.partnerType} set={v=>setRuleForm({...ruleForm,partnerType:v})} options={["",...partnerTypes]} names={["Any partner type",...partnerTypes]}/>
        <Field label="Project ID (optional)" type="number" value={ruleForm.projectId} onChange={e=>setRuleForm({...ruleForm,projectId:e.target.value})}/>
        <Field label="Unit category (optional)" value={ruleForm.unitCategory} onChange={e=>setRuleForm({...ruleForm,unitCategory:e.target.value})}/>
        <Select label="Booking source (optional)" value={ruleForm.bookingSource} set={v=>setRuleForm({...ruleForm,bookingSource:v})} options={["","Website","WalkIn","Phone","Referral","Other"]} names={["Any booking source","Website","Walk-in","Phone","Referral","Other"]}/>
        <Field label="Booking ID (optional)" type="number" value={ruleForm.bookingId} onChange={e=>setRuleForm({...ruleForm,bookingId:e.target.value})}/>
        <Field label="Minimum commission" type="number" min="0" step="0.01" value={ruleForm.minimumCommission} onChange={e=>setRuleForm({...ruleForm,minimumCommission:e.target.value})}/>
        <Field label="Maximum commission" type="number" min="0" step="0.01" value={ruleForm.maximumCommission} onChange={e=>setRuleForm({...ruleForm,maximumCommission:e.target.value})}/>
        <div className="sm:col-span-2"><Field as="textarea" label="Description" value={ruleForm.description} onChange={e=>setRuleForm({...ruleForm,description:e.target.value})}/></div>
        <div className="sm:col-span-2"><Field as="textarea" label="Notes" value={ruleForm.notes} onChange={e=>setRuleForm({...ruleForm,notes:e.target.value})}/></div>
        {ruleForm.id&&<div className="sm:col-span-2"><Field as="textarea" label="Change reason" required value={ruleForm.changeReason} onChange={e=>setRuleForm({...ruleForm,changeReason:e.target.value})}/></div>}
        <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={ruleForm.isActive} onChange={e=>setRuleForm({...ruleForm,isActive:e.target.checked})}/> Active</label>
        <Actions saving={saving} close={()=>setRuleForm(null)}/>
      </form>
    </Modal>}
  </Container>;
}

function Stat({label,value,danger=false}:{label:string;value:string;danger?:boolean}){return <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><p className="text-xs text-[var(--text-muted)]">{label}</p><p className={`mt-2 text-xl font-bold ${danger?"text-rose-400":"text-[var(--text-heading)]"}`}>{value}</p></div>}
function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-[var(--border)] bg-[var(--surface-glass-hover)]">{headers.map(h=><th key={h} className="p-4 text-xs font-semibold uppercase tracking-wide text-[var(--text-muted)]">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Cell({children}:{children:ReactNode}){return <td className="p-4 text-[var(--text-secondary)]">{children}</td>}
function Badge({value}:{value:string}){const risky=value.includes("Reversal")||value==="Cancelled";const good=value==="Active"||value==="Paid"||value==="Applied";return <span className={`rounded-full border px-2.5 py-1 text-xs ${risky?"border-rose-500/30 bg-rose-500/10 text-rose-300":good?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":"border-amber-500/30 bg-amber-500/10 text-amber-200"}`}>{prettyEnum(value)}</span>}
function Empty({text}:{text:string}){return <p className="rounded-2xl border border-dashed border-[var(--border)] p-10 text-center text-sm text-[var(--text-muted)]">{text}</p>}
function Pager({page,hasMore,setPage}:{page:number;hasMore:boolean;setPage:(page:number)=>void}){return <div className="mt-4 flex items-center justify-end gap-3 text-sm"><button className="rounded-lg border border-[var(--border)] px-3 py-2 disabled:opacity-40" disabled={page===0} onClick={()=>setPage(Math.max(0,page-1))}>Previous</button><span className="text-[var(--text-muted)]">Page {page+1}</span><button className="rounded-lg border border-[var(--border)] px-3 py-2 disabled:opacity-40" disabled={!hasMore} onClick={()=>setPage(page+1)}>Next</button></div>}
function Filters({search,setSearch,value,setValue,options}:{search:string;setSearch:(v:string)=>void;value:string;setValue:(v:string)=>void;options:string[]}){return <div className="mb-4 flex gap-3"><input aria-label="Search partners" placeholder="Search partner, code, contact or tax ID" value={search} onChange={e=>setSearch(e.target.value)} className={`${selectClass} flex-1`}/><select aria-label="Partner status" value={value} onChange={e=>setValue(e.target.value)} className={selectClass}>{options.map(o=><option key={o} value={o}>{prettyEnum(o)}</option>)}</select></div>}
function RecordsFilter({value,setValue,values}:{value:string;setValue:(v:string)=>void;values:{v:string;n:string}[]}){return <div className="mb-4 flex justify-end"><select aria-label="Record status" value={value} onChange={e=>setValue(e.target.value)} className={selectClass}><option value="">All statuses</option>{values.map(o=><option key={o.v} value={o.v}>{o.n}</option>)}</select></div>}
function Select({label,value,set,options,names}:{label:string;value:string;set:(v:string)=>void;options:string[];names?:string[]}){return <label className="flex flex-col gap-1.5 text-sm font-medium text-[var(--text-secondary)]">{label}<select value={value} onChange={e=>set(e.target.value)} className={selectClass}>{options.map((o,i)=><option key={`${o}-${i}`} value={o}>{names?.[i]??prettyEnum(o)}</option>)}</select></label>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button aria-label="Close dialog" onClick={close} className="absolute inset-0 bg-black/70"/><section autoFocus tabIndex={-1} onKeyDown={e=>trapDialogKeys(e,close)} role="dialog" aria-modal="true" aria-label={title} className="relative max-h-[92dvh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-[var(--border)] bg-[var(--modal-bg)] p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button aria-label="Close" onClick={close}>✕</button></div>{children}</section></div>}
function Actions({saving,close}:{saving:boolean;close:()=>void}){return <div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="ghost" onClick={close} disabled={saving}>Cancel</Button><Button type="submit" disabled={saving}>{saving?"Saving…":"Save"}</Button></div>}
function FormError({text}:{text:string}){return <p role="alert" className="rounded-xl bg-rose-500/10 p-3 text-sm text-rose-300 sm:col-span-2">{text}</p>}
