import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import type { User } from "../App";
import { api } from "../api/api";
import Button from "../lib/Button";
import Container from "../lib/Container";
import StatCard from "../lib/StatCard";

type Account = { id:number; name:string; type:number; accountHolderName:string; openingBalance:number; bankOrWalletName:string|null; description:string|null; isActive:boolean; revenueReceived:number; expensesPaid:number; netMovement:number; currentBalance:number; transactionCount:number; concurrencyToken:string };
type Transaction = { kind:string; recordId:number; date:string; label:string; reference:string|null; projectName:string; amount:number };
type Overview = { activeAccounts:number; inactiveAccounts:number; totalBalance:number; holderBalances:{accountHolderName:string;accountCount:number;currentBalance:number}[] };
type Form = { id:number|null; name:string; type:string; accountHolderName:string; openingBalance:string; bankOrWalletName:string; description:string; concurrencyToken:string };
const types = ["Cash", "Bank", "Mobile Wallet", "Other"];
const emptyForm = ():Form => ({ id:null, name:"", type:"1", accountHolderName:"", openingBalance:"0", bankOrWalletName:"", description:"", concurrencyToken:"" });
const money = (n:number) => `Rs ${n.toLocaleString("en-PK", { maximumFractionDigits:2 })}`;

export default function FinanceAccountsPage({ user }:{user:User|null}) {
  const navigate = useNavigate();
  const [accounts,setAccounts]=useState<Account[]>([]), [loading,setLoading]=useState(true), [search,setSearch]=useState(""), [status,setStatus]=useState("all");
  const [typeFilter,setTypeFilter]=useState(""), [holderFilter,setHolderFilter]=useState("");
  const [form,setForm]=useState<Form|null>(null), [saving,setSaving]=useState(false), [error,setError]=useState<string|null>(null);
  const [selected,setSelected]=useState<Account|null>(null), [transactions,setTransactions]=useState<Transaction[]>([]);
  const [overview,setOverview]=useState<Overview|null>(null);
  const loadOverview=useCallback(async()=>{try{const r=await api("/api/finance/accounts/overview");if(r.ok)setOverview(await r.json());}catch{/* Summary cards retain their last successful values. */}},[]);
  const load=useCallback(async()=>{ setLoading(true); try { const p=new URLSearchParams({take:"200"}); if(search)p.set("search",search); if(status!=="all")p.set("isActive",String(status==="active")); if(typeFilter)p.set("type",typeFilter); if(holderFilter)p.set("holder",holderFilter); const r=await api(`/api/finance/accounts?${p}`); if(!r.ok) throw new Error("Accounts could not be loaded."); setAccounts((await r.json()).items); await loadOverview(); } catch { setAccounts([]); } finally { setLoading(false); } },[search,status,typeFilter,holderFilter,loadOverview]);
  useEffect(()=>{ if(user?.role!=="Admin"){navigate("/");return;} const timer=window.setTimeout(()=>void load(),0); return()=>window.clearTimeout(timer); },[user,navigate,load]);
  const openDetail=async(a:Account)=>{setSelected(a);setTransactions([]);try{const [detail,tx]=await Promise.all([api(`/api/finance/accounts/${a.id}`),api(`/api/finance/accounts/${a.id}/transactions?take=200`)]);if(detail.ok)setSelected(await detail.json());if(tx.ok)setTransactions((await tx.json()).items);}catch{/* Empty history is shown with a safe fallback. */}};
  const save=async()=>{ if(!form||saving)return; setError(null); if(!form.name.trim()||!form.accountHolderName.trim()){setError("Account name and account holder are required.");return;} const opening=Number(form.openingBalance); if(!Number.isFinite(opening)){setError("Enter a valid opening balance.");return;} setSaving(true); try { const body={name:form.name.trim(),type:Number(form.type),accountHolderName:form.accountHolderName.trim(),openingBalance:opening,bankOrWalletName:form.bankOrWalletName.trim()||null,description:form.description.trim()||null,concurrencyToken:form.concurrencyToken}; const r=await api(form.id?`/api/finance/accounts/${form.id}`:"/api/finance/accounts",{method:form.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.message??"Account could not be saved.");} setForm(null);await load(); } catch(saveError) { setError(saveError instanceof Error?saveError.message:"Account could not be saved. Check your connection and try again."); } finally { setSaving(false); } };
  const edit=(a:Account)=>setForm({id:a.id,name:a.name,type:String(a.type),accountHolderName:a.accountHolderName,openingBalance:String(a.openingBalance),bankOrWalletName:a.bankOrWalletName??"",description:a.description??"",concurrencyToken:a.concurrencyToken});
  const toggle=async(a:Account)=>{const action=a.isActive?"deactivate":"reactivate";if(!confirm(`${action[0].toUpperCase()+action.slice(1)} ${a.name}? Historical transactions will be preserved.`))return;try{const r=await api(`/api/finance/accounts/${a.id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({isActive:!a.isActive,concurrencyToken:a.concurrencyToken})});if(!r.ok)throw new Error((await r.json().catch(()=>null))?.message??"Status could not be changed.");await load();}catch(statusError){alert(statusError instanceof Error?statusError.message:"Status could not be changed. Check your connection and try again.");}};
  return <Container className="py-8">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Link to="/finance" className="text-sm text-[var(--accent)]">← Finance dashboard</Link><h1 className="mt-1 text-2xl font-bold text-[var(--text-heading)]">Finance Accounts</h1><p className="text-sm text-[var(--text-muted)]">Cash, bank and wallet accounts used by revenue and expenses.</p></div><Button onClick={()=>setForm(emptyForm())}>Add Account</Button></div>
    <div className="stat-grid mb-5"><StatCard tone="muted" label="Active accounts" value={String(overview?.activeAccounts??0)}/><StatCard tone="muted" label="Combined balance" value={money(overview?.totalBalance??0)}/><StatCard tone="muted" label="Account holders" value={String(overview?.holderBalances.length??0)}/></div>
    <div className="mb-4 flex flex-wrap gap-3"><input aria-label="Search accounts" className="min-w-[200px] flex-1 rounded-xl border border-[var(--border)] bg-[var(--bg-card)] px-4 py-2 text-[var(--text-primary)]" placeholder="Search account, holder, bank or wallet" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter by type" className="rounded-xl border border-[var(--border)] bg-[var(--bg-card)] px-3 text-[var(--text-primary)]" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">All types</option>{types.map((t,i)=><option key={t} value={i+1}>{t}</option>)}</select><select aria-label="Filter by holder" className="rounded-xl border border-[var(--border)] bg-[var(--bg-card)] px-3 text-[var(--text-primary)]" value={holderFilter} onChange={e=>setHolderFilter(e.target.value)}><option value="">All holders</option>{overview?.holderBalances.map(h=><option key={h.accountHolderName} value={h.accountHolderName}>{h.accountHolderName}</option>)}</select><select aria-label="Filter by status" className="rounded-xl border border-[var(--border)] bg-[var(--bg-card)] px-3 text-[var(--text-primary)]" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All status</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
    <div className="overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--bg-card)]"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-[var(--border)] text-left text-[var(--text-muted)]">{["Account","Type / holder","Opening","Revenue","Expenses","Current balance","Status","Actions"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{accounts.map(a=><tr key={a.id} className="border-b border-[var(--border)]"><td className="p-4 font-semibold text-[var(--text-heading)]"><button onClick={()=>void openDetail(a)} className="text-left hover:underline">{a.name}</button><div className="text-xs font-normal text-[var(--text-muted)]">{a.bankOrWalletName}</div></td><td className="p-4">{types[a.type-1] ?? "—"}<div className="text-xs text-[var(--text-muted)]">{a.accountHolderName}</div></td><td className="p-4">{money(a.openingBalance)}</td><td className="p-4 text-emerald-400">{money(a.revenueReceived)}</td><td className="p-4 text-rose-400">{money(a.expensesPaid)}</td><td className="p-4 font-semibold">{money(a.currentBalance)}</td><td className="p-4"><span className={a.isActive?"text-emerald-400":"text-[var(--text-muted)]"}>{a.isActive?"Active":"Inactive"}</span></td><td className="p-4"><div className="flex gap-2"><button className="text-[var(--accent)]" onClick={()=>edit(a)}>Edit</button><button className="text-[var(--text-muted)]" onClick={()=>void toggle(a)}>{a.isActive?"Deactivate":"Reactivate"}</button></div></td></tr>)}</tbody></table>{loading&&<p className="p-6 text-center text-[var(--text-muted)]">Loading…</p>}{!loading&&!accounts.length&&<p className="p-8 text-center text-[var(--text-muted)]">No finance accounts found.</p>}</div>
    {form&&<Modal title={form.id?"Edit Finance Account":"Add Finance Account"} close={()=>!saving&&setForm(null)}><div className="space-y-4">{error&&<p className="rounded-lg bg-rose-500/10 p-3 text-sm text-rose-300">{error}</p>}<Field label="Account Name" value={form.name} set={v=>setForm({...form,name:v})}/><label className="block text-sm text-[var(--text-muted)]">Account Type<select className="mt-1 w-full rounded-xl border border-[var(--border)] bg-[var(--bg-card)] p-3 text-[var(--text-primary)]" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map((t,i)=><option value={i+1} key={t}>{t}</option>)}</select></label><Field label="Account Holder Name" value={form.accountHolderName} set={v=>setForm({...form,accountHolderName:v})}/><Field label="Opening Balance (Rs)" type="number" value={form.openingBalance} set={v=>setForm({...form,openingBalance:v})}/><Field label="Bank / Wallet Name (optional)" value={form.bankOrWalletName} set={v=>setForm({...form,bankOrWalletName:v})}/><Field label="Description (optional)" value={form.description} set={v=>setForm({...form,description:v})}/><div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setForm(null)} disabled={saving}>Cancel</Button><Button onClick={()=>void save()} disabled={saving}>{saving?"Saving…":"Save"}</Button></div></div></Modal>}
    {selected&&<DetailModal account={selected} transactions={transactions} close={()=>setSelected(null)}/>}
  </Container>;
}
function DetailModal({account,transactions,close}:{account:Account;transactions:Transaction[];close:()=>void}){
  const fullHistory = transactions.length >= account.transactionCount;
  const orderedAsc = [...transactions].sort((a,b)=> a.date===b.date ? a.recordId-b.recordId : (a.date<b.date?-1:1));
  let running = account.openingBalance;
  const rows = orderedAsc.map(t=>{ running += t.amount; return { t, balance: running }; });
  return <Modal title={account.name} close={close}>
    <p className="mb-3 text-sm text-[var(--text-muted)]">{types[account.type-1] ?? "—"} · {account.accountHolderName}{account.bankOrWalletName?` · ${account.bankOrWalletName}`:""}{account.isActive?"":" · Inactive"}</p>
    <div className="stat-grid mb-4"><StatCard tone="muted" label="Opening balance" value={money(account.openingBalance)}/><StatCard tone="muted" label="Current balance" value={money(account.currentBalance)}/><StatCard tone="emerald" label="Revenue received" value={money(account.revenueReceived)}/><StatCard tone="rose" label="Expenses paid" value={money(account.expensesPaid)}/></div>
    <h3 className="mb-2 font-semibold">Transaction history</h3>
    {!transactions.length
      ? <p className="py-8 text-center text-sm text-[var(--text-muted)]">No transactions assigned to this account.</p>
      : <div className="max-h-80 space-y-2 overflow-y-auto">
          {fullHistory&&<div className="flex items-center justify-between rounded-xl border border-dashed border-[var(--border)] p-3 text-[var(--text-muted)]"><span className="font-medium">Opening balance</span><span>{money(account.openingBalance)}</span></div>}
          {rows.map(({t,balance})=><div key={`${t.kind}-${t.recordId}`} className="flex items-center justify-between rounded-xl border border-[var(--border)] p-3"><div><p className="font-medium">{t.label}</p><p className="text-xs text-[var(--text-muted)]">{new Date(t.date).toLocaleDateString("en-GB")} · {t.projectName}{t.reference?` · ${t.reference}`:""}</p></div><div className="text-right"><span className={t.amount>=0?"text-emerald-400":"text-rose-400"}>{t.amount>=0?"+":""}{money(t.amount)}</span>{fullHistory&&<p className="text-xs text-[var(--text-muted)]">Balance {money(balance)}</p>}</div></div>)}
          {!fullHistory&&<p className="pt-1 text-center text-xs text-[var(--text-muted)]">Showing the {transactions.length} most recent transactions; running balance hidden.</p>}
        </div>}
  </Modal>;
}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="block text-sm text-[var(--text-muted)]">{label}<input type={type} className="mt-1 w-full rounded-xl border border-[var(--border)] bg-[var(--bg-card)] p-3 text-[var(--text-primary)]" value={value} onChange={e=>set(e.target.value)}/></label>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button aria-label="Close" className="absolute inset-0 bg-black/60" onClick={close}/><div className="relative max-h-[92dvh] w-full max-w-xl overflow-y-auto rounded-2xl border border-[var(--border)] bg-[var(--modal-bg)] p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="text-xl font-semibold">{title}</h2><button onClick={close}>✕</button></div>{children}</div></div>}
