import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import type { User } from "../App";
import { api } from "../api/api";
import Button from "../lib/Button";
import Container from "../lib/Container";

type Partner = { id:number; name:string; cnic:string|null; ntn:string|null; profitSharePercent:number; financeAccountId:number|null; financeAccountName:string|null; isActive:boolean; joinedDate:string|null; exitedDate:string|null; openingBalance:number; contributions:number; withdrawals:number; profitShare:number; lossShare:number; closingBalance:number; concurrencyToken:string };
type CashAccount = { id:number; name:string; accountHolderName:string; isActive:boolean };
type CapitalAccount = CashAccount & { type:string|number };
type Transaction = { id:number; type:string; amount:number; date:string; financeAccountId:number|null; reference:string|null; note:string|null; profitSharePercentSnapshot:number|null };
type Statement = { partnerId:number; partnerName:string; from:string|null; to:string|null; openingBalance:number; transactions:Transaction[]; closingBalance:number };
type PartnerForm = { id:number|null; name:string; cnic:string; ntn:string; profitSharePercent:string; financeAccountId:string; joinedDate:string; exitedDate:string; concurrencyToken:string };
const TYPES = [ ["Contribution","Contribution"], ["Withdrawal","Withdrawal"], ["ProfitShare","Profit share"], ["LossShare","Loss share"] ];
const money = (value:number) => `Rs ${value.toLocaleString("en-PK", { maximumFractionDigits:2 })}`;
const today = () => { const date=new Date(), pad=(n:number)=>String(n).padStart(2,"0"); return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`; };

export default function FinancePartnersPage({user}:{user:User|null}) {
  const navigate=useNavigate();
  const [partners,setPartners]=useState<Partner[]>([]), [accounts,setAccounts]=useState<CashAccount[]>([]);
  const [capitalAccounts,setCapitalAccounts]=useState<CapitalAccount[]>([]), [activeStates,setActiveStates]=useState<Record<number,boolean>>({});
  const [loading,setLoading]=useState(true), [error,setError]=useState<string|null>(null), [savingShares,setSavingShares]=useState(false);
  const [shares,setShares]=useState<Record<number,string>>({});
  const [partnerForm,setPartnerForm]=useState<PartnerForm|null>(null), [savingPartner,setSavingPartner]=useState(false);
  const [transactionPartner,setTransactionPartner]=useState<Partner|null>(null), [statement,setStatement]=useState<Statement|null>(null);
  const [recordingTransaction,setRecordingTransaction]=useState(false);
  const [form,setForm]=useState({type:"Contribution",amount:"",date:today(),financeAccountId:"",reference:"",note:""});

  const load=useCallback(async()=>{setLoading(true);setError(null);try{const [partnerResponse,accountResponse,allAccountResponse]=await Promise.all([api("/api/finance/partners?includeInactive=true"),api("/api/finance/accounts/options?includeInactive=true&cashLikeOnly=true"),api("/api/finance/accounts/options?includeInactive=true&cashLikeOnly=false")]);if(!partnerResponse.ok)throw new Error((await partnerResponse.json().catch(()=>null))?.message??"Partners could not be loaded.");const rows=await partnerResponse.json() as Partner[];setPartners(rows);setShares(Object.fromEntries(rows.map(row=>[row.id,String(row.profitSharePercent)])));setActiveStates(Object.fromEntries(rows.map(row=>[row.id,row.isActive])));if(accountResponse.ok)setAccounts(await accountResponse.json());if(allAccountResponse.ok){const all=await allAccountResponse.json() as CapitalAccount[];setCapitalAccounts(all.filter(account=>account.type==="Capital"||Number(account.type)===6));}}catch(caught){setError(caught instanceof Error?caught.message:"Partners could not be loaded.");}finally{setLoading(false);}},[]);
  useEffect(()=>{if(user?.role!=="Admin"){navigate("/");return;}void load();},[user,navigate,load]);

  const total=partners.filter(partner=>activeStates[partner.id]).reduce((sum,partner)=>sum+(Number(shares[partner.id])||0),0);
  const saveShares=async()=>{setSavingShares(true);setError(null);try{const response=await api("/api/finance/partners/shares",{method:"PUT",body:JSON.stringify({partners:partners.map(partner=>({id:partner.id,profitSharePercent:Number(shares[partner.id]),isActive:Boolean(activeStates[partner.id]),concurrencyToken:partner.concurrencyToken}))})});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message??"Shares could not be saved.");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Shares could not be saved.");}finally{setSavingShares(false);}};
  const savePartner=async()=>{if(!partnerForm)return;const share=Number(partnerForm.profitSharePercent);if(!partnerForm.name.trim()||!Number.isFinite(share)||share<0||share>100){setError("Enter a partner name and a share between 0% and 100%.");return;}setSavingPartner(true);setError(null);try{const existing=partnerForm.id?partners.find(row=>row.id===partnerForm.id):null;const response=await api(partnerForm.id?`/api/finance/partners/${partnerForm.id}`:"/api/finance/partners",{method:partnerForm.id?"PUT":"POST",body:JSON.stringify({name:partnerForm.name.trim(),cnic:partnerForm.cnic.trim()||null,ntn:partnerForm.ntn.trim()||null,profitSharePercent:share,financeAccountId:Number(partnerForm.financeAccountId)||null,isActive:existing?.isActive??false,joinedDate:partnerForm.joinedDate||null,exitedDate:partnerForm.exitedDate||null,concurrencyToken:partnerForm.concurrencyToken})});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message??"Partner could not be saved.");setPartnerForm(null);await load();}catch(caught){setError(caught instanceof Error?caught.message:"Partner could not be saved.");}finally{setSavingPartner(false);}};
  const openStatement=async(partner:Partner)=>{setError(null);try{const response=await api(`/api/finance/partners/${partner.id}/statement`);if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message??"Statement could not be loaded.");setStatement(await response.json());}catch(caught){setError(caught instanceof Error?caught.message:"Statement could not be loaded.");}};
  const saveTransaction=async()=>{if(!transactionPartner||recordingTransaction)return;const amount=Number(form.amount);if(!Number.isFinite(amount)||amount<=0){setError("Enter an amount greater than zero.");return;}const movesCash=form.type==="Contribution"||form.type==="Withdrawal";if(movesCash&&!form.financeAccountId){setError("Choose the cash or bank account used.");return;}setRecordingTransaction(true);setError(null);try{const response=await api(`/api/finance/partners/${transactionPartner.id}/transactions`,{method:"POST",body:JSON.stringify({type:form.type,amount,date:form.date,financeAccountId:movesCash?Number(form.financeAccountId)||null:null,reference:form.reference||null,note:form.note||null})});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message??"Transaction could not be saved.");setTransactionPartner(null);setForm({type:"Contribution",amount:"",date:today(),financeAccountId:"",reference:"",note:""});await load();}catch(caught){setError(caught instanceof Error?caught.message:"Transaction could not be saved.");}finally{setRecordingTransaction(false);}};

  if(user?.role!=="Admin")return null;
  return <Container className="py-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><Link to="/finance/reports" className="text-sm text-[var(--accent)]">← Financial reports</Link><h1 className="mt-1 text-3xl font-bold text-[var(--text-heading)]">Capital Partners</h1><p className="text-sm text-[var(--text-muted)]">Partner capital, frozen distribution shares, and double-sided bank movements.</p></div><div className="flex gap-2"><Link to="/finance/accounts"><Button variant="outline">Capital Accounts</Button></Link><Button onClick={()=>setPartnerForm({id:null,name:"",cnic:"",ntn:"",profitSharePercent:"0",financeAccountId:"",joinedDate:"",exitedDate:"",concurrencyToken:""})}>Add partner</Button></div></div>
  {error&&<p className="mb-4 rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">{error}</p>}
  <div className={`mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4 ${Math.abs(total-100)<=.01?"border-emerald-500/30 bg-emerald-500/5":"border-rose-500/40 bg-rose-500/10"}`}><div><p className="font-semibold">Active profit shares: {total.toFixed(4)}%</p><p className="text-xs text-[var(--text-muted)]">All active partners must total 100%. Historical ProfitShare transactions keep their original percentage snapshot.</p></div><Button disabled={savingShares||Math.abs(total-100)>.01} onClick={()=>void saveShares()}>{savingShares?"Saving…":"Save shares"}</Button></div>
  <div className="overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><table className="w-full min-w-[1200px] text-sm"><thead><tr className="border-b border-[var(--border)] text-left text-[var(--text-muted)]">{["Partner","Active / share %","Opening","Contributions","Withdrawals","Profit share","Loss share","Closing","Actions"].map(label=><th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{partners.map(partner=><tr key={partner.id} className="border-b border-[var(--border)]"><td className="p-3 font-semibold">{partner.name}<p className="text-xs font-normal text-[var(--text-muted)]">{partner.financeAccountName??"No capital account"}{partner.isActive?"":" · Inactive"}</p></td><td className="p-3"><div className="flex items-center gap-2"><input aria-label={`${partner.name} active`} type="checkbox" checked={Boolean(activeStates[partner.id])} onChange={event=>setActiveStates({...activeStates,[partner.id]:event.target.checked})}/><input aria-label={`${partner.name} profit share`} type="number" step="0.0001" min="0" max="100" className="w-24 rounded-lg border border-[var(--border)] bg-[var(--input-bg)] px-2 py-1" value={shares[partner.id]??""} onChange={event=>setShares({...shares,[partner.id]:event.target.value})} disabled={!activeStates[partner.id]}/></div></td><td className="p-3">{money(partner.openingBalance)}</td><td className="p-3 text-emerald-300">{money(partner.contributions)}</td><td className="p-3 text-rose-300">{money(partner.withdrawals)}</td><td className="p-3">{money(partner.profitShare)}</td><td className="p-3">{money(partner.lossShare)}</td><td className="p-3 font-bold">{money(partner.closingBalance)}</td><td className="p-3"><div className="flex gap-2"><button className="text-[var(--accent)]" onClick={()=>setPartnerForm({id:partner.id,name:partner.name,cnic:partner.cnic??"",ntn:partner.ntn??"",profitSharePercent:String(partner.profitSharePercent),financeAccountId:partner.financeAccountId?String(partner.financeAccountId):"",joinedDate:partner.joinedDate?.slice(0,10)??"",exitedDate:partner.exitedDate?.slice(0,10)??"",concurrencyToken:partner.concurrencyToken})}>Edit</button><button className="text-[var(--accent)]" onClick={()=>void openStatement(partner)}>Statement</button><button className="text-[var(--accent)]" disabled={!partner.isActive} onClick={()=>{setError(null);setTransactionPartner(partner);}}>Add transaction</button></div></td></tr>)}</tbody></table>{loading&&<p className="p-10 text-center text-[var(--text-muted)]">Loading partners…</p>}</div>
  {partnerForm&&<Modal title={partnerForm.id?`Edit partner · ${partnerForm.name}`:"Add capital partner"} close={()=>!savingPartner&&setPartnerForm(null)}><div className="space-y-4"><Field label="Name" value={partnerForm.name} set={value=>setPartnerForm({...partnerForm,name:value})}/><div className="grid gap-3 sm:grid-cols-2"><Field label="CNIC" value={partnerForm.cnic} set={value=>setPartnerForm({...partnerForm,cnic:value})}/><Field label="NTN" value={partnerForm.ntn} set={value=>setPartnerForm({...partnerForm,ntn:value})}/></div><Field label="Profit share %" type="number" disabled={partnerForm.id!==null} value={partnerForm.profitSharePercent} set={value=>setPartnerForm({...partnerForm,profitSharePercent:value})}/>{partnerForm.id&&<p className="text-xs text-[var(--text-muted)]">Change existing shares together in the table so the active allocation remains exactly 100%.</p>}<Select label="Capital account" value={partnerForm.financeAccountId} set={value=>setPartnerForm({...partnerForm,financeAccountId:value})}><option value="">Select account</option>{capitalAccounts.filter(account=>(account.isActive||String(account.id)===partnerForm.financeAccountId)&&!partners.some(partner=>partner.id!==partnerForm.id&&partner.financeAccountId===account.id)).map(account=><option key={account.id} value={account.id}>{account.name}{account.isActive?"":" (Inactive)"}</option>)}</Select><div className="grid gap-3 sm:grid-cols-2"><Field label="Joined date" type="date" value={partnerForm.joinedDate} set={value=>setPartnerForm({...partnerForm,joinedDate:value})}/><Field label="Exited date" type="date" value={partnerForm.exitedDate} set={value=>setPartnerForm({...partnerForm,exitedDate:value})}/></div>{!partnerForm.id&&<p className="text-xs text-[var(--text-muted)]">New partners start inactive. Activate them and rebalance all active shares together in the table.</p>}<div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setPartnerForm(null)}>Cancel</Button><Button disabled={savingPartner} onClick={()=>void savePartner()}>{savingPartner?"Saving…":"Save partner"}</Button></div></div></Modal>}
  {transactionPartner&&<Modal title={`Capital transaction · ${transactionPartner.name}`} close={()=>!recordingTransaction&&setTransactionPartner(null)}><div className="space-y-4"><Select label="Type" value={form.type} set={value=>setForm({...form,type:value})}>{TYPES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select><Field label="Amount (Rs)" type="number" value={form.amount} set={value=>setForm({...form,amount:value})}/><Field label="Date" type="date" value={form.date} set={value=>setForm({...form,date:value})}/>{(form.type==="Contribution"||form.type==="Withdrawal")&&<Select label="Cash / bank account" value={form.financeAccountId} set={value=>setForm({...form,financeAccountId:value})}><option value="">Select account</option>{accounts.filter(account=>account.isActive).map(account=><option key={account.id} value={account.id}>{account.name} · {account.accountHolderName}</option>)}</Select>}<Field label="Reference" value={form.reference} set={value=>setForm({...form,reference:value})}/><Field label="Note" value={form.note} set={value=>setForm({...form,note:value})}/><div className="flex justify-end gap-2"><Button variant="ghost" disabled={recordingTransaction} onClick={()=>setTransactionPartner(null)}>Cancel</Button><Button disabled={recordingTransaction} onClick={()=>void saveTransaction()}>{recordingTransaction?"Recording…":"Record transaction"}</Button></div></div></Modal>}
  {statement&&<Modal title={`${statement.partnerName} · Statement`} close={()=>setStatement(null)}><div className="mb-3 flex justify-between rounded-xl bg-[var(--surface-glass)] p-3"><span>Opening balance</span><strong>{money(statement.openingBalance)}</strong></div><div className="max-h-96 space-y-2 overflow-y-auto">{statement.transactions.map(row=>{const decrease=row.type==="Withdrawal"||row.type==="LossShare"||row.amount<0;return <div key={row.id} className="flex justify-between rounded-xl border border-[var(--border)] p-3"><div><p className="font-semibold">{String(row.type).replace(/([A-Z])/g," $1").trim()}</p><p className="text-xs text-[var(--text-muted)]">{new Date(row.date).toLocaleDateString("en-GB")}{row.reference?` · ${row.reference}`:""}{row.profitSharePercentSnapshot!=null?` · ${row.profitSharePercentSnapshot}% snapshot`:""}</p></div><strong>{decrease?"−":"+"}{money(Math.abs(row.amount))}</strong></div>;})}{!statement.transactions.length&&<p className="py-8 text-center text-[var(--text-muted)]">No transactions.</p>}</div><div className="mt-3 flex justify-between rounded-xl bg-[var(--surface-glass)] p-3"><span>Closing balance</span><strong>{money(statement.closingBalance)}</strong></div></Modal>}
  </Container>;
}
function Field({label,value,set,type="text",disabled=false}:{label:string;value:string;set:(value:string)=>void;type?:string;disabled?:boolean}){return <label className="block text-sm text-[var(--text-muted)]">{label}<input disabled={disabled} className="mt-1 w-full rounded-xl border border-[var(--border)] bg-[var(--input-bg)] p-3 disabled:opacity-60" type={type} value={value} onChange={event=>set(event.target.value)}/></label>}
function Select({label,value,set,children}:{label:string;value:string;set:(value:string)=>void;children:React.ReactNode}){return <label className="block text-sm text-[var(--text-muted)]">{label}<select className="mt-1 w-full rounded-xl border border-[var(--border)] bg-[var(--input-bg)] p-3" value={value} onChange={event=>set(event.target.value)}>{children}</select></label>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button aria-label="Close" className="absolute inset-0 bg-black/60" onClick={close}/><div className="relative max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-[var(--border)] bg-[var(--modal-bg)] p-6"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={close}>✕</button></div>{children}</div></div>}
